#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=30gb,walltime=8:00:00
#PBS -N app-trekker-roi-tracking


[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

dtiinit=`jq -r '.dtiinit' config.json`
if [[ ${dtiinit} == "null" ]]; then
        DIFF=`jq -r '.dwi' config.json`
        BVALS=`jq -r '.bvals' config.json`
        BVECS=`jq -r '.bvecs' config.json`
else
        BVALS=$dtiinit/dwi_aligned*.bvals
        BVECS=$dtiinit/dwi_aligned*.bvecs
        DIFF=$dtiinit/dwi_aligned*.nii.gz
fi
#echo "reslicing rois"
time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer-mini:6.0.1 ./resliceROI.sh $DIFF

if [ ! -f csf_bin.nii.gz ]; then
	time singularity exec -e docker://brainlife/mrtrix3:3.0.0 ./preprocess.sh
fi

time singularity exec -e docker://brainlife/trekker:0.6 ./tracking.py

if [ ! -f ./track/track.tck ]; then
	time singularity exec -e docker://brainlife/mrtrix3:3.0.0 ./convert.sh
fi
#
#if [ ! -f ./wmc/classification.mat ]; then
#	time singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/classificationGenerator
#fi
#
#if [ -f ./wmc/classification.mat ]; then
#	mv *track*.txt track*.tck ./raw/
#	echo "complete"
#	exit 0
#else
#	echo "tracking failed"
#	exit 1
#fi
