#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=30gb,walltime=8:00:00
#PBS -N app-trekker-roi-tracking

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

dtiinit=`jq -r '.dtiinit' config.json`
if [[ ${dtiinit} == "null" ]]; then
        DIFF=`jq -r '.dwi' config.json`
        BVALS=`jq -r '.bvals' config.json`
        BVECS=`jq -r '.bvecs' config.json`
else
        BVALS=$dtiinit/dwi_aligned*.bvals
        BVECS=$dtiinit/dwi_aligned*.bvecs
        DIFF=$dtiinit/dwi_aligned*.nii.gz
fi
#echo "reslicing rois"
time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer-mini:6.0.1 ./resliceROI.sh $DIFF

time singularity exec -e docker://brainlife/trekker:0.4 ./run.sh

time singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/classificationGenerator

mv *track_* track*.json track*.vtk track*.tck ./raw/
